/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.sistemarestaurantepresentacion;

import itson.sistemarestaurantedominio.dtos.IngredienteRegistradoDTO;
import itson.sistemarestaurantenegocio.IIngredientesBO;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.List;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author saula
 */
public class BuscadorIngredientesPanel extends javax.swing.JPanel implements IngredientesRegistradosListener{

    private static final String DEFAULT_BUSCADOR = "INGRESE EL INGREDIENTE QUE DESEA BUSCAR";
    private IngredientesRegistradosListener listener;
    private IIngredientesBO ingredientesBO;
    /**
     * Creates new form BuscadorIngredientesPanel
     * @param ingredientesBO
     * @param listener
     */
    public BuscadorIngredientesPanel(IIngredientesBO ingredientesBO, IngredientesRegistradosListener listener) {
        initComponents();
        configurarPlaceholders();
        configurarBusquedaEnTiempoReal();
        this.ingredientesBO = ingredientesBO;
        this.listener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textFieldBuscador = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        comboBoxUnidad = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textFieldBuscador.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        textFieldBuscador.setForeground(new java.awt.Color(204, 204, 204));
        textFieldBuscador.setText("INGRESE EL INGREDIENTE QUE DESEA BUSCAR");
        textFieldBuscador.setBorder(null);
        textFieldBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBuscadorActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 310, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 30, 400, 5));

        comboBoxUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "PIEZAS", "GRAMOS", "MILILITROS" }));
        jPanel1.add(comboBoxUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void configurarPlaceholder(javax.swing.JTextField textField, String placeholderText) {
        // Establecer el texto y color inicial
        textField.setText(placeholderText);
        textField.setForeground(Color.GRAY);

        // Agregar FocusListener para manejar el comportamiento del placeholder
        textField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                // Cuando el campo obtiene el foco
                if (textField.getText().equals(placeholderText)) {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                // Cuando el campo pierde el foco
                if (textField.getText().isEmpty()) {
                    textField.setText(placeholderText);
                    textField.setForeground(Color.GRAY);
                }
            }
        });
    }

    private void configurarPlaceholders() {
        configurarPlaceholder(textFieldBuscador, DEFAULT_BUSCADOR);
    }
    
        private void configurarBusquedaEnTiempoReal() {
        textFieldBuscador.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                actualizarBusqueda();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                actualizarBusqueda();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                actualizarBusqueda();
            }
        });
    }
    
    private void actualizarBusqueda(){
        String filtro = textFieldBuscador.getText().trim();
        String unidad = comboBoxUnidad.getSelectedItem().toString();

            List<IngredienteRegistradoDTO> resultados = ingredientesBO.buscarIngredientePorFiltro(filtro, unidad);

            if (listener != null)
                listener.onIngredientesRegistrados(resultados);
            
    }
        
    private void textFieldBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBuscadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxUnidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField textFieldBuscador;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onIngredientesRegistrados(List<IngredienteRegistradoDTO> ingredientes) {
    }
}
