/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.sistemarestaurantepresentacion;

import itson.sistemarestaurantedominio.ClienteFrecuente;
import itson.sistemarestaurantenegocio.IClientesFrecuentesBO;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rauln
 */
public class ClientesFrecuentes extends javax.swing.JFrame implements ClientesFiltradosListener{

    private DefaultTableModel modeloTabla;
    private JTable tablaResultados;
    private JScrollPane jScrollPane1;
    private IClientesFrecuentesBO clientesFrecuentesBO;
    private ClientesFiltradosListener listener;


    public ClientesFrecuentes(IClientesFrecuentesBO clientesFrecuentesBO) {
        this.clientesFrecuentesBO = clientesFrecuentesBO;
        initComponents();
        crearTabla();

        // Configura el listener para que la clase ClientesFrecuentes reciba los resultados filtrados
        buscadorClientesFrecuentesPanel1.setClientesFiltradosListener(this);
        buscadorClientesFrecuentesPanel1.setClientesFrecuentesBO(clientesFrecuentesBO);
        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 600, 350));
    }

    
    @Override
    public void onClientesFiltrados(List<ClienteFrecuente> clientes) {
        actualizarTabla(clientes);
    }

    private void obtenerClientesDesdeBuscador(String filtro) {
        if (clientesFrecuentesBO != null) {
            List<ClienteFrecuente> clientes = clientesFrecuentesBO.buscarClientes(filtro);
            actualizarTabla(clientes);
        }
    }

    private void crearTabla() {
        modeloTabla = new DefaultTableModel(new String[]{"Nombre", "Teléfono", "Correo"}, 0);
        tablaResultados = new JTable(modeloTabla);
        jScrollPane1 = new JScrollPane(tablaResultados);
    }

    public void actualizarTabla(List<ClienteFrecuente> clientes) {
        modeloTabla.setRowCount(0);
        for (ClienteFrecuente cliente : clientes) {
            modeloTabla.addRow(new Object[]{cliente.getNombre(), cliente.getTelefono(), cliente.getCorreo()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscadorClientesFrecuentesPanel1 = new itson.sistemarestaurantepresentacion.BuscadorClientesFrecuentesPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(buscadorClientesFrecuentesPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.sistemarestaurantepresentacion.BuscadorClientesFrecuentesPanel buscadorClientesFrecuentesPanel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
