/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.sistemarestaurantepresentacion;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author rauln
 */
public class Comandas extends javax.swing.JFrame {

    /**
     * Creates new form Comandas
     */
    public Comandas() {
        initComponents();
        inicializarTabla();
    }

    private void inicializarTabla() {
        // Cargar la imagen de lupa
        ImageIcon lupaIcon = new ImageIcon(getClass().getResource("/lupa2.png"));

        // Modelo de la tabla
        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Comanda", "Mesa", "Estado", "Revisar"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Todas las celdas no son editables
            }
        };

        JTable table = new JTable(model);

        try {
            // Cargar la fuente Montserrat
            Font montserrat = Font.createFont(Font.TRUETYPE_FONT, new File("resources/Montserrat-Medium.ttf")).deriveFont(12f);
            Font montserratHeader = montserrat.deriveFont(Font.BOLD, 14f);

            // Aplicar al header
            JTableHeader header = table.getTableHeader();
            header.setFont(montserratHeader);

            // Aplicar a las filas
            table.setFont(montserrat);
            table.setRowHeight(40); // Ajustar altura de las filas

        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
            // Si falla la carga de fuente, se usa la predeterminada
        }

        // Centrar columnas de texto
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        table.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        table.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        table.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);

        // Renderizador para la columna de icono
        table.getColumnModel().getColumn(3).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus,
                    int row, int column) {
                JLabel label = new JLabel();
                label.setHorizontalAlignment(JLabel.CENTER);
                label.setIcon(lupaIcon);
                return label;
            }
        });
        
        table.setRowHeight(40);
        JTableHeader header = table.getTableHeader();
        header.setFont(new Font("Montserrat", Font.BOLD, 14));
        header.setBackground(new Color(60, 63, 65)); // Fondo gris oscuro
        header.setForeground(Color.WHITE); // Texto blanco
        header.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1)); // Borde negro delgado

        // Crear JScrollPane y agregar la tabla
        JScrollPane scrollPane = new JScrollPane(table);
        scrollPane.setBounds(20, 70, 760, 350); // Ubicar la tabla debajo del texto
        fondo.setLayout(null); // Layout absoluto
        fondo.add(scrollPane); // Añadir JScrollPane al panel fondo

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        labelTexto1 = new javax.swing.JLabel();
        botonAgregarComanda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTexto1.setFont(new java.awt.Font("Montserrat Medium", 1, 24)); // NOI18N
        labelTexto1.setText("COMANDAS");
        fondo.add(labelTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 40, 160, -1));

        botonAgregarComanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonAgregarComanda.png"))); // NOI18N
        fondo.add(botonAgregarComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 300, 40));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonAgregarComanda;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel labelTexto1;
    // End of variables declaration//GEN-END:variables
}
