/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.sistemarestaurantepresentacion;

import itson.sistemarestaurantedominio.dtos.IngredienteRegistradoDTO;
import itson.sistemarestaurantenegocio.IIngredientesBO;
import itson.sistemarestaurantenegocio.excepciones.StockInvalidoException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saula
 */
public class InventarioIngredientesForm extends javax.swing.JFrame implements IngredientesRegistradosListener {

    private DefaultTableModel modeloTabla;
    private JTable tablaResultados;
    private JScrollPane jScrollPane1;
    private IIngredientesBO ingredientesBO;
    private IngredientesRegistradosListener listener;
    
    /**
     * Creates new form InventarioIngredientesForm
     */
    public InventarioIngredientesForm(IIngredientesBO ingredientesBO) {
        this.ingredientesBO = ingredientesBO;
        initComponents();
        crearTabla();
        buscadorIngredientesPanel1.iniciarBusqueda(ingredientesBO, this);
        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 600, 350)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscadorIngredientesPanel1 = new itson.sistemarestaurantepresentacion.BuscadorIngredientesPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(buscadorIngredientesPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void onIngredientesRegistrados(List<IngredienteRegistradoDTO> ingredientes) {
        actualizarTabla(ingredientes);
    }

    private void crearTabla() {
        modeloTabla = new DefaultTableModel(new String[]{"ID", "Nombre", "Stock", "Unidad"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // solo la columna 2 (stock) se puede editar, la 1 es el id pero está escondido
                return column == 2; 
            }
        };
        tablaResultados = new JTable(modeloTabla);
        jScrollPane1 = new JScrollPane(tablaResultados);
        
        //escondo la columna del id
        tablaResultados.getColumnModel().getColumn(0).setMinWidth(0);
        tablaResultados.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaResultados.getColumnModel().getColumn(0).setWidth(0);
        
        modeloTabla.addTableModelListener((TableModelEvent e) -> {
            if (e.getType() == TableModelEvent.UPDATE) {
                int fila = e.getFirstRow();
                int columna = e.getColumn();
                
                if (columna == 2) {
                    Long id = (Long) modeloTabla.getValueAt(fila, 0);
                    String nuevoStockTexto = modeloTabla.getValueAt(fila, columna).toString();
                    
                    try {
                        ingredientesBO.actualizarStockIngrediente(id, nuevoStockTexto);
                    } catch (StockInvalidoException ex) {
                        JOptionPane.showMessageDialog(jPanel1, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });
    }
    
    public void actualizarTabla(List<IngredienteRegistradoDTO> ingredientes) {
        modeloTabla.setRowCount(0);
        for (IngredienteRegistradoDTO ing : ingredientes) 
            modeloTabla.addRow(new Object[]{
                ing.getId(),
                ing.getNombre(), 
                ing.getStock(), 
                ing.getUnidadMedidaIngrediente().toString()
            });    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.sistemarestaurantepresentacion.BuscadorIngredientesPanel buscadorIngredientesPanel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}