/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.sistemarestaurantepresentacion;

import itson.sistemarestaurantepresentacion.control.Control;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author saula
 */
public class PantallaAdministradorForm extends javax.swing.JFrame {

    /**
     * Creates new form PantallaAdministradorForm
     */
    public PantallaAdministradorForm() {
        initComponents();
        setTitle("ADMINISTRADOR");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        add(new JLabel("Pantalla de administrador", SwingConstants.CENTER));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backround = new javax.swing.JPanel();
        botonMesas = new javax.swing.JLabel();
        botonComandas = new javax.swing.JLabel();
        botonClientes = new javax.swing.JLabel();
        botonProductos = new javax.swing.JLabel();
        botonIngredientes = new javax.swing.JLabel();
        botonReportes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backround.setBackground(new java.awt.Color(255, 255, 255));

        botonMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonMesas.png"))); // NOI18N
        botonMesas.setText("jLabel1");
        botonMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMesasMouseClicked(evt);
            }
        });

        botonComandas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonComandas.png"))); // NOI18N
        botonComandas.setText("jLabel2");
        botonComandas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonComandasMouseClicked(evt);
            }
        });

        botonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonClientes{.png"))); // NOI18N
        botonClientes.setText("jLabel3");
        botonClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonClientesMouseClicked(evt);
            }
        });

        botonProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonProductos.png"))); // NOI18N
        botonProductos.setText("jLabel4");
        botonProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonProductosMouseClicked(evt);
            }
        });

        botonIngredientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonIngrediente.png"))); // NOI18N
        botonIngredientes.setText("jLabel5");
        botonIngredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIngredientesMouseClicked(evt);
            }
        });

        botonReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonReportes.png"))); // NOI18N
        botonReportes.setText("jLabel6");
        botonReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonReportesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backroundLayout = new javax.swing.GroupLayout(backround);
        backround.setLayout(backroundLayout);
        backroundLayout.setHorizontalGroup(
            backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backroundLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(botonMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(91, 91, 91)
                .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        backroundLayout.setVerticalGroup(
            backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backroundLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMesas)
                    .addComponent(botonComandas)
                    .addComponent(botonClientes))
                .addGap(50, 50, 50)
                .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonProductos)
                    .addComponent(botonIngredientes)
                    .addComponent(botonReportes))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        botonMesas.getAccessibleContext().setAccessibleName("botonMesas");
        botonComandas.getAccessibleContext().setAccessibleName("botonComandas");
        botonClientes.getAccessibleContext().setAccessibleName("botonClientes");
        botonProductos.getAccessibleContext().setAccessibleName("botonProductos");
        botonProductos.getAccessibleContext().setAccessibleDescription("");
        botonIngredientes.getAccessibleContext().setAccessibleName("botonIngredientes");
        botonReportes.getAccessibleContext().setAccessibleName("botonReportes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMesasMouseClicked
        Control.getInstancia().abrirMesas();
    }//GEN-LAST:event_botonMesasMouseClicked

    private void botonComandasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComandasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonComandasMouseClicked

    private void botonClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonClientesMouseClicked
        Control.getInstancia().abrirClientesFrecuentes();
    }//GEN-LAST:event_botonClientesMouseClicked

    private void botonProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProductosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonProductosMouseClicked

    private void botonIngredientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngredientesMouseClicked
        Control.getInstancia().abrirInventarioIngredientes();
    }//GEN-LAST:event_botonIngredientesMouseClicked

    private void botonReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReportesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonReportesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backround;
    private javax.swing.JLabel botonClientes;
    private javax.swing.JLabel botonComandas;
    private javax.swing.JLabel botonIngredientes;
    private javax.swing.JLabel botonMesas;
    private javax.swing.JLabel botonProductos;
    private javax.swing.JLabel botonReportes;
    // End of variables declaration//GEN-END:variables
}
