/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.sistemarestaurantepresentacion;

import itson.sistemarestaurantedominio.UnidadMedidaIngrediente;
import itson.sistemarestaurantedominio.dtos.NuevoIngredienteDTO;
import itson.sistemarestaurantenegocio.IIngredientesBO;
import itson.sistemarestaurantenegocio.excepciones.IngredienteRegistradoException;
import itson.sistemarestaurantenegocio.excepciones.NombreInvalidoException;
import itson.sistemarestaurantenegocio.excepciones.StockInvalidoException;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JOptionPane;

/**
 *
 * @author saula
 */
public class RegistrarIngredienteForm extends javax.swing.JFrame {
    
    private static final String NOMBRE_DEFAULT = "INGRESE EL NOMBRE DEL INGREDIENTE";
    private static final String STOCK_DEFAULT = "INGRESE EL STOCK INICIAL";
    
    private IIngredientesBO ingredientesBO;
    /**
     * Creates new form RegistrarIngredienteForm
     */
    public RegistrarIngredienteForm(IIngredientesBO ingredientesBO) {
        initComponents();
        configurarPlaceholders();
        this.ingredientesBO = ingredientesBO;
    }
    
   public void limpiarFormulario(){
       textFieldIngresarNombre.setText("");
       comboBoxUnidadMedida.setSelectedIndex(0);
       textFieldIngresarStock.setText("");
   }
   
   // Método para configurar un campo de texto con su placeholder

    private void configurarPlaceholder(javax.swing.JTextField textField, String placeholderText) {
        // Establecer el texto y color inicial
        textField.setText(placeholderText);
        textField.setForeground(Color.GRAY);

        // Agregar FocusListener para manejar el comportamiento del placeholder
        textField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                // Cuando el campo obtiene el foco
                if (textField.getText().equals(placeholderText)) {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                // Cuando el campo pierde el foco
                if (textField.getText().isEmpty()) {
                    textField.setText(placeholderText);
                    textField.setForeground(Color.GRAY);
                }
            }
        });
    }

    // Método para configurar los placeholders en todos los campos
    private void configurarPlaceholders() {
        configurarPlaceholder(textFieldIngresarNombre, NOMBRE_DEFAULT);
        configurarPlaceholder(textFieldIngresarStock, STOCK_DEFAULT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        labelUnidadMedida = new javax.swing.JLabel();
        registrarNuevoIngredienteTxt2 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelStock = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        botonRegistrar = new javax.swing.JLabel();
        textFieldIngresarStock = new javax.swing.JTextField();
        comboBoxUnidadMedida = new javax.swing.JComboBox<>();
        textFieldIngresarNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setMinimumSize(new java.awt.Dimension(300, 400));
        background.setPreferredSize(new java.awt.Dimension(300, 400));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUnidadMedida.setFont(new java.awt.Font("Montserrat SemiBold", 1, 12)); // NOI18N
        labelUnidadMedida.setText("UNIDAD DE MEDIDA");
        background.add(labelUnidadMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        registrarNuevoIngredienteTxt2.setFont(new java.awt.Font("Montserrat SemiBold", 1, 12)); // NOI18N
        registrarNuevoIngredienteTxt2.setText("REGISTRAR NUEVO INGREDIENTE");
        background.add(registrarNuevoIngredienteTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        labelNombre.setFont(new java.awt.Font("Montserrat SemiBold", 1, 12)); // NOI18N
        labelNombre.setText("NOMBRE");
        background.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        labelStock.setFont(new java.awt.Font("Montserrat SemiBold", 1, 12)); // NOI18N
        labelStock.setText("STOCK");
        background.add(labelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 105, 240, 5));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 155, 240, 5));
        background.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 305, 240, 5));

        botonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/REGISTRAR.png"))); // NOI18N
        botonRegistrar.setToolTipText("");
        botonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseClicked(evt);
            }
        });
        background.add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 100, 40));

        textFieldIngresarStock.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        textFieldIngresarStock.setForeground(new java.awt.Color(204, 204, 204));
        textFieldIngresarStock.setText("INGRESE EL STOCK INICIAL");
        textFieldIngresarStock.setBorder(null);
        textFieldIngresarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIngresarStockActionPerformed(evt);
            }
        });
        background.add(textFieldIngresarStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 250, -1));

        comboBoxUnidadMedida.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        comboBoxUnidadMedida.setForeground(new java.awt.Color(204, 204, 204));
        comboBoxUnidadMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PIEZAS", "GRAMOS", "MILILITROS" }));
        comboBoxUnidadMedida.setBorder(null);
        comboBoxUnidadMedida.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxUnidadMedidaItemStateChanged(evt);
            }
        });
        comboBoxUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxUnidadMedidaActionPerformed(evt);
            }
        });
        background.add(comboBoxUnidadMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 250, 20));
        comboBoxUnidadMedida.setSelectedIndex(1);

        textFieldIngresarNombre.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        textFieldIngresarNombre.setForeground(new java.awt.Color(204, 204, 204));
        textFieldIngresarNombre.setText("INGRESE EL NOMBRE DEL INGREDIENTE");
        textFieldIngresarNombre.setBorder(null);
        textFieldIngresarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIngresarNombreActionPerformed(evt);
            }
        });
        background.add(textFieldIngresarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseClicked
        try{
            String nombre = textFieldIngresarNombre.getText().trim();
            float stock = Float.parseFloat(textFieldIngresarStock.getText());
            String unidadSeleccionada = comboBoxUnidadMedida.getSelectedItem().toString();
            UnidadMedidaIngrediente unidadMedida = UnidadMedidaIngrediente.valueOf(unidadSeleccionada);
       
            NuevoIngredienteDTO ingredienteDTO = new NuevoIngredienteDTO(nombre, unidadMedida, stock);
            this.ingredientesBO.registrar(ingredienteDTO);
            
            JOptionPane.showMessageDialog(background, "Registro de ingrediente exitoso!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarFormulario();
        }catch(IngredienteRegistradoException | NombreInvalidoException | StockInvalidoException e){
            JOptionPane.showMessageDialog(background, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonRegistrarMouseClicked

    private void comboBoxUnidadMedidaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxUnidadMedidaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxUnidadMedidaItemStateChanged

    private void comboBoxUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxUnidadMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxUnidadMedidaActionPerformed

    private void textFieldIngresarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIngresarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIngresarNombreActionPerformed

    private void textFieldIngresarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIngresarStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIngresarStockActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel botonRegistrar;
    private javax.swing.JComboBox<String> comboBoxUnidadMedida;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelStock;
    private javax.swing.JLabel labelUnidadMedida;
    private javax.swing.JLabel registrarNuevoIngredienteTxt2;
    private javax.swing.JTextField textFieldIngresarNombre;
    private javax.swing.JTextField textFieldIngresarStock;
    // End of variables declaration//GEN-END:variables
}
