package itson.sistemarestaurantepresentacion.buscadores;

import itson.sistemarestaurantedominio.Producto;
import itson.sistemarestaurantenegocio.implementaciones.ProductosBO;
import itson.sistemarestaurantepersistencia.implementaciones.ProductosDAO;
import itson.sistemarestaurantepersistencia.implementaciones.ManejadorConexiones;


import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.List;

/**
 *
 * @author ssanchez
 */
public class BuscadorProductoForm extends javax.swing.JFrame {

    //private JTextField campoBusqueda;
    //private JTable tablaProductos;
    //private JButton btnRegistrarProducto;

//  private ProductosBO productosBO = new ProductosBO();
   // private ProductosBO productosBO = new ProductosBO(new ProductosDAO(new ManejadorConexiones()));
    
    private ProductosBO productosBO = new ProductosBO(
      new ProductosDAO(ManejadorConexiones.getEntityManager())
    );


    
    
    /**
     * Creates new form BuscadorProductoForm
     */
    public BuscadorProductoForm() {
        setTitle("Productos");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(600, 400);
        setLocationRelativeTo(null);
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
        modelo.setRowCount(0); // limpia los datos de prueba

        //cargarProductos("");
        cargarProductosIniciales();
        
    }

//private void initComponents() {    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        registrarNuevoIngredienteTxt7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRegistrarProducto = new javax.swing.JLabel();
        campoBusqueda = new javax.swing.JTextField();
        Lupa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setMinimumSize(new java.awt.Dimension(300, 400));
        background.setPreferredSize(new java.awt.Dimension(300, 400));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrarNuevoIngredienteTxt7.setFont(new java.awt.Font("Montserrat SemiBold", 1, 12)); // NOI18N
        registrarNuevoIngredienteTxt7.setText("PRODUCTOS");
        background.add(registrarNuevoIngredienteTxt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 320, 10));

        btnRegistrarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/REGISTRAR.png"))); // NOI18N
        btnRegistrarProducto.setToolTipText("");
        background.add(btnRegistrarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 100, 40));

        campoBusqueda.setBackground(new java.awt.Color(153, 153, 153));
        campoBusqueda.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        campoBusqueda.setForeground(new java.awt.Color(204, 204, 204));
        campoBusqueda.setBorder(null);
        campoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBusquedaActionPerformed(evt);
            }
        });
        background.add(campoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 340, 30));

        Lupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa2.png"))); // NOI18N
        background.add(Lupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "NOMBRE", "PRECIO", "Tipo de Producto"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 390, 275));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void cargarProductos(String filtro) {
        try {
            List<Producto> productos = productosBO.buscarProductos(filtro);
            DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
            modelo.setRowCount(0);
            for (Producto producto : productos) {
                modelo.addRow(new Object[] {
                        producto.getNombre(),
                        "$" + producto.getPrecio() + " MXN",
                        producto.getTipoProducto()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar productos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void abrirRegistro(ActionEvent evt) {
        itson.sistemarestaurantepresentacion.pantallaregistros.RegistrarProductoForm form = new itson.sistemarestaurantepresentacion.pantallaregistros.RegistrarProductoForm();
        form.setVisible(true);
    }

       
    
    private void cargarProductosIniciales() {
        try {
            List<Producto> productos = productosBO.cargaInicial();
            DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
            modelo.setRowCount(0);
            int limite = Math.min(5, productos.size());
            for (int i = 0; i < limite; i++) {
                Producto producto = productos.get(i);
                modelo.addRow(new Object[] {
                        producto.getNombre(),
                        "$" + producto.getPrecio() + " MXN",
                        producto.getTipoProducto()
                });
            }
            //lanza a consola la cantidad de productos.
            System.out.println("Total productos encontrados: " + productos.size());
            for (Producto p : productos) {
                System.out.println(p.getNombre() + " - $" + p.getPrecio() + " - " + p.getTipoProducto());
             }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar productos iniciales: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

       
    
    
    /*      */   //aqui termina MouseLCicked
    
    private void campoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscadorProductoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscadorProductoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscadorProductoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscadorProductoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new BuscadorProductoForm().setVisible(true);
                SwingUtilities.invokeLater(() -> new BuscadorProductoForm().setVisible(true));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lupa;
    private javax.swing.JPanel background;
    private javax.swing.JLabel btnRegistrarProducto;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel registrarNuevoIngredienteTxt7;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
