package itson.sistemarestaurantepresentacion.buscadores;

import itson.sistemarestaurantedominio.Producto;
import itson.sistemarestaurantenegocio.implementaciones.ProductosBO;
import itson.sistemarestaurantepersistencia.implementaciones.ProductosDAO;
import itson.sistemarestaurantepersistencia.implementaciones.ManejadorConexiones;


import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.List;

/**
 *
 * @author ssanchez
 */
public class BuscadorProductoForm extends javax.swing.JFrame {

    //private JTextField campoBusqueda;
    //private JTable tablaProductos;
    //private JButton btnRegistrarProducto;

    //private ProductosBO productosBO = new ProductosBO();
   // private ProductosBO productosBO = new ProductosBO(new ProductosDAO(new ManejadorConexiones()));
    private ProductosBO productosBO = new ProductosBO(
      new ProductosDAO(ManejadorConexiones.getEntityManager())
    );


    
    
    /**
     * Creates new form BuscadorProductoForm
     */
    public BuscadorProductoForm() {
        setTitle("Productos");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(600, 400);
        setLocationRelativeTo(null);
        initComponents();
        cargarProductos("");
    }

private void initComponents() {
        JPanel panel = new JPanel(new BorderLayout(10, 10));
        JPanel panelSuperior = new JPanel(new BorderLayout(5, 5));

        JLabel lblBuscar = new JLabel(new ImageIcon(getClass().getResource("/lupa2.png")));
        campoBusqueda = new JTextField();
        campoBusqueda.setFont(new Font("SansSerif", Font.PLAIN, 14));
        campoBusqueda.setToolTipText("Buscar por nombre o tipo...");

        campoBusqueda.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { buscar(); }
            public void removeUpdate(DocumentEvent e) { buscar(); }
            public void changedUpdate(DocumentEvent e) { buscar(); }
            private void buscar() {
                cargarProductos(campoBusqueda.getText());
            }
        });

        panelSuperior.add(lblBuscar, BorderLayout.WEST);
        panelSuperior.add(campoBusqueda, BorderLayout.CENTER);

        tablaProductos = new JTable(new DefaultTableModel(
                new Object[][] {},
                new String[] {"Nombre", "Precio", "Tipo de Producto"}
        ));
        JScrollPane scrollPane = new JScrollPane(tablaProductos);

        //btnRegistrarProducto = new JButton("Registrar Producto");
        //btnRegistrarProducto.addActionListener(this::abrirRegistro);

        JPanel panelInferior = new JPanel();
        panelInferior.add(btnRegistrarProducto);

        panel.add(panelSuperior, BorderLayout.NORTH);
        panel.add(scrollPane, BorderLayout.CENTER);
        panel.add(panelInferior, BorderLayout.SOUTH);

        add(panel);
    }

    private void cargarProductos(String filtro) {
        try {
            List<Producto> productos = productosBO.buscarProductos(filtro);
            DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
            modelo.setRowCount(0);
            for (Producto producto : productos) {
                modelo.addRow(new Object[] {
                        producto.getNombre(),
                        "$" + producto.getPrecio() + " MXN",
                        producto.getTipoProducto()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar productos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void abrirRegistro(ActionEvent evt) {
        itson.sistemarestaurantepresentacion.pantallaregistros.RegistrarProductoForm form = new itson.sistemarestaurantepresentacion.pantallaregistros.RegistrarProductoForm();
        form.setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        registrarNuevoIngredienteTxt7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRegistrarProducto = new javax.swing.JLabel();
        campoBusqueda = new javax.swing.JTextField();
        labelNombre2 = new javax.swing.JLabel();
        Lupa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setMinimumSize(new java.awt.Dimension(300, 400));
        background.setPreferredSize(new java.awt.Dimension(300, 400));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrarNuevoIngredienteTxt7.setFont(new java.awt.Font("Montserrat SemiBold", 1, 12)); // NOI18N
        registrarNuevoIngredienteTxt7.setText("PRODUCTO");
        background.add(registrarNuevoIngredienteTxt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 320, 10));

        btnRegistrarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/REGISTRAR.png"))); // NOI18N
        btnRegistrarProducto.setToolTipText("");
        btnRegistrarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarProductoMouseClicked(evt);
            }
        });
        background.add(btnRegistrarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 100, 40));

        campoBusqueda.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        campoBusqueda.setForeground(new java.awt.Color(204, 204, 204));
        campoBusqueda.setBorder(null);
        campoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBusquedaActionPerformed(evt);
            }
        });
        background.add(campoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 330, 20));

        labelNombre2.setFont(new java.awt.Font("Montserrat SemiBold", 1, 12)); // NOI18N
        labelNombre2.setText("BUSCAR PRODUCTO");
        background.add(labelNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 220, -1));

        Lupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa2.png"))); // NOI18N
        background.add(Lupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "INGREDIENTES", "UNIDAD", "CANTIDAD"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 390, 275));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    private void btnRegistrarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarProductoMouseClicked
        try{

            String nombreProducto = campoBusqueda.getText().trim();
            float precio = Float.parseFloat(campoPrecio.getText().trim());
            TipoProducto tipoProducto = TipoProducto.valueOf(textFieldingresarTipoDeProducto.getSelectedItem().toString());

            NuevoProductoDTO nuevoProducto = new NuevoProductoDTO(nombreProducto, precio, tipoProducto);
            nuevoProducto.setIngredientes(ingredientesSeleccionados);

            Producto producto = productosBO.registrarProducto(nuevoProducto);

            JOptionPane.showMessageDialog(this, "Producto registrado con éxito: " + producto.getNombre());
            limpiarFormulario();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Precio inválido.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al registrar: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        /////////

    }//GEN-LAST:event_btnRegistrarProductoMouseClicked
      */   //aqui termina MouseLCicked
    
    private void campoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscadorProductoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscadorProductoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscadorProductoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscadorProductoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new BuscadorProductoForm().setVisible(true);
                SwingUtilities.invokeLater(() -> new BuscadorProductoForm().setVisible(true));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lupa;
    private javax.swing.JPanel background;
    private javax.swing.JLabel btnRegistrarProducto;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelNombre2;
    private javax.swing.JLabel registrarNuevoIngredienteTxt7;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
